name: Test two actions
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: managedkaos/github-actions-two-actions/action1@master
      - uses: managedkaos/github-actions-two-actions/action2@master
